version: '2'

services:

### Workspace Utilities Container ###########################

    nodejs:
        image: gokusenz/dockergk:nodejs
        volumes_from:
            - volumes_source
        ports:
            - "8080:8080"

### MongoDB Container #######################################

    mongo:
        image: gokusenz/dockergk:mongo
        ports:
            - "27017:27017"
        volumes_from:
            - volumes_data

### Application Code Container ######################

    volumes_source:
        image: tianon/true
        volumes:
            - .:/usr/src/app

### Databases Data Container ################################

    volumes_data:
        image: tianon/true
        volumes:
            - ./data/mongo:/data/db
